#!/usr/bin/env python3
"""Create leakage-aware clean train and held-out manifests.

The raw folder split contains a small number of exact duplicate files that
appear in both training and held-out test. For reproducible evaluation, this
script keeps the held-out test split fixed and removes exact duplicate hashes
from the training manifest only.
"""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        type=Path,
        default=Path("data_quality/dataset_manifest.csv"),
        help="Input dataset manifest generated by build_dataset_manifest.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data_quality"),
        help="Directory for clean split outputs.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    manifest = pd.read_csv(args.manifest)
    heldout_hashes = set(manifest.loc[manifest["split"] == "heldout_test", "sha256"].dropna())

    train = manifest[manifest["split"] == "train"].copy()
    heldout = manifest[manifest["split"] == "heldout_test"].copy()

    clean_train = train[~train["sha256"].isin(heldout_hashes)].copy()
    removed_train = train[train["sha256"].isin(heldout_hashes)].copy()

    clean_train_path = args.output_dir / "clean_train_manifest.csv"
    heldout_path = args.output_dir / "heldout_test_manifest.csv"
    removed_path = args.output_dir / "removed_train_leakage_rows.csv"
    summary_path = args.output_dir / "clean_split_summary.csv"
    db_path = args.output_dir / "image_dataset.sqlite"

    clean_train.to_csv(clean_train_path, index=False)
    heldout.to_csv(heldout_path, index=False)
    removed_train.to_csv(removed_path, index=False)

    summary = pd.DataFrame(
        [
            {"metric": "raw_train_rows", "value": int(len(train))},
            {"metric": "clean_train_rows", "value": int(len(clean_train))},
            {"metric": "heldout_test_rows", "value": int(len(heldout))},
            {"metric": "removed_train_exact_leakage_rows", "value": int(len(removed_train))},
            {
                "metric": "removed_train_exact_leakage_hashes",
                "value": int(removed_train["sha256"].nunique()),
            },
        ]
    )
    summary.to_csv(summary_path, index=False)

    if db_path.exists():
        with sqlite3.connect(db_path) as conn:
            clean_train.to_sql("clean_train_manifest", conn, if_exists="replace", index=False)
            heldout.to_sql("heldout_test_manifest", conn, if_exists="replace", index=False)
            removed_train.to_sql("removed_train_leakage_rows", conn, if_exists="replace", index=False)
            summary.to_sql("clean_split_summary", conn, if_exists="replace", index=False)
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_clean_train_label ON clean_train_manifest(label)"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_heldout_test_label ON heldout_test_manifest(label)"
            )

    print(f"Wrote clean train manifest: {clean_train_path} ({len(clean_train):,} rows)")
    print(f"Wrote held-out test manifest: {heldout_path} ({len(heldout):,} rows)")
    print(f"Wrote removed leakage rows: {removed_path} ({len(removed_train):,} rows)")
    print(f"Wrote clean split summary: {summary_path}")
    if len(removed_train):
        print(
            "Removed train rows with exact hashes found in held-out test: "
            f"{len(removed_train):,} rows / {removed_train['sha256'].nunique():,} hashes"
        )


if __name__ == "__main__":
    main()
